### ISSUE TITLE
Share on Instagram

### ISSUE THREAD

**Issue by Hamza-Ikhlaq** [wololock/hexo-tag-share-post#7]
Hey @wololock, I hope you're having a good day. With ```hexo-tag-share-post``` plugin I can able to share my blog posts on Facebook, Twitter, and Linkedin. I'm here to ask you that it this possible to share my blog post on Instagram as well with this plugin. Take a look at the following code which I used.

```
share_post:
  instagram:
    url: 'https://www.instagram.com/'
    query: 'u=%link&t=%title'
    text: 'Share on Instagram'  
```
Looking forward to your review.

Regards
Hamza
